from __future__ import annotations

from aih_contexture.middle.schema import CANONICAL_BLOCK_TYPES


_LABEL_ALIASES = {
    "text": "Text",
    "plain_text": "Text",
    "body": "Text",
    "paragraph": "Text",
    "content": "Text",
    "abstract": "Text",
    "phonetic": "Text",
    "vertical_text": "Text",
    "index": "ListItem",
    "ref_text": "Reference",
    "title": "SectionHeader",
    "doctitle": "SectionHeader",
    "doc_title": "SectionHeader",
    "document_title": "SectionHeader",
    "paragraph_title": "SectionHeader",
    "section_header": "SectionHeader",
    "sectionheader": "SectionHeader",
    "heading": "SectionHeader",
    "header": "PageHeader",
    "page_header": "PageHeader",
    "pageheader": "PageHeader",
    "footer": "PageFooter",
    "page_footer": "PageFooter",
    "pagefooter": "PageFooter",
    "page_number": "PageNumber",
    "number": "PageNumber",
    "footnote": "Footnote",
    "page_footnote": "Footnote",
    "image_footnote": "Footnote",
    "table_footnote": "Footnote",
    "chart_footnote": "Footnote",
    "code_footnote": "Footnote",
    "vision_footnote": "Footnote",
    "aside_text": "MarginalNote",
    "page_aside_text": "MarginalNote",
    "marginal_note": "MarginalNote",
    "marginal_note_left": "MarginalNote",
    "marginal_note_right": "MarginalNote",
    "marginalannotation": "MarginalNote",
    "marginal_annotation": "MarginalNote",
    "inline_annotation": "InlineAnnotation",
    "inlineannotation": "InlineAnnotation",
    "reference": "Reference",
    "reference_content": "Reference",
    "caption": "Caption",
    "table_caption": "Caption",
    "image_caption": "Caption",
    "chart_caption": "Caption",
    "algorithm_caption": "Caption",
    "code_caption": "Caption",
    "figure_title": "Caption",
    "table_title": "Caption",
    "chart_title": "Caption",
    "figure_caption": "Caption",
    "figure": "Figure",
    "image": "Picture",
    "image_description": "ImageDescription",
    "image_desc": "ImageDescription",
    "picture": "Picture",
    "chart": "Figure",
    "chart_body": "Figure",
    "seal": "Figure",
    "image_body": "Picture",
    "header_image": "PageHeader",
    "footer_image": "PageFooter",
    "table": "Table",
    "table_body": "Table",
    "simple_table": "Table",
    "complex_table": "Table",
    "formula": "Equation",
    "display_formula": "Equation",
    "inline_formula": "Equation",
    "formula_number": "Equation",
    "equation": "Equation",
    "equation_block": "Equation",
    "math": "Equation",
    "interline_equation": "Equation",
    "equation_interline": "Equation",
    "inline_equation": "Equation",
    "equation_inline": "Equation",
    "isolate_formula": "Equation",
    "list": "ListItem",
    "list_group": "ListItem",
    "list_item": "ListItem",
    "listitem": "ListItem",
    "text_list": "ListItem",
    "reference_list": "Reference",
    "code": "Code",
    "code_inline": "Code",
    "code_block": "Code",
    "code_body": "Code",
    "algorithm": "Code",
    "form": "Form",
    "handwriting": "Handwriting",
    "table_of_contents": "TableOfContents",
    "tableofcontents": "TableOfContents",
    "toc": "TableOfContents",
    "complex_region": "ComplexRegion",
    "complexregion": "ComplexRegion",
    "discarded": "ComplexRegion",
    "md": "Text",
    "hyperlink": "Reference",
}


def normalize_block_type(raw_label: str | None) -> str:
    if not raw_label:
        return "ComplexRegion"

    compact = raw_label.strip().replace("-", "_").replace(" ", "_")
    key = compact.lower()
    if key in _LABEL_ALIASES:
        return _LABEL_ALIASES[key]

    pascal = compact.replace("_", " ").title().replace(" ", "")
    if pascal in CANONICAL_BLOCK_TYPES:
        return pascal

    return "ComplexRegion"
